update workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -88,8 +88,11 @@ jobs:
         id: healthcheck
         run: |
           STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.GCP_VM_IP }}:8000/va/healthcheck/)
+          echo "HTTP Status Code: $STATUS_CODE"
           echo "status=$STATUS_CODE" >> $GITHUB_ENV
 
       - name: Fail if Container is not Running
-        run: exit 1
-        if: env.status != '200'
+        run: |
+          echo "Health check failed! Status code: ${{ env.status }}"
+          exit 1
+        if: ${{ env.status != '200' }}
